import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    en: {
        translation: {
            "Introduction": "Introduction",
            "Summary": "Summary",
            "name":"Joaquin",
            "see":"View more",
            "seeCode":"View code",
            "heroTitle1": "I am a Full Stack Developer experienced in the React ecosystem (React, Next.js, React Native) and Kotlin for native Android applications. I have also worked with neural networks, enabling me to integrate AI solutions into my projects.",
            "heroTitle2":"My main focus is on building dynamic, engaging user interfaces and robust, secure backend services using Spring Boot and Node/Express. I bring experience with SQL and NoSQL databases, paying special attention to code quality, scalability, and performance optimization.",
            "heroTitle3":"Beyond my technical expertise, I am passionate about innovation and tackling complex problems, always striving to create genuine value for end users. I firmly believe in continuous improvement and collaborative work to develop high-impact solutions in the tech market.",
            "Get in touch": "Get in touch",
            "Contact": "Contact",
            "Your Name": "Your Name",
            "What's your name?":"What's your name?",
            "Your email": "Your email",
            "What is your email address?":"What is your email address?",
            "Your Message": "Your Message",
            "What you want to say?":"What you want to say?",
            "Send": "Send",
            "Sending...": "Sending...",
            "Hi, I'm Joaquin": "Hi, I'm",
            "developer full stack, user interfaces and web applications": "Developer full stack, user interfaces and web applications",
            "Thank you. I will get back to you as soon as possible.": "Thank you. I will get back to you as soon as possible.",
            "Ahh, something went wrong. Please try again.": "Ahh, something went wrong. Please try again.",
            "Featured Works": "Featured Works",
            "Next.js Web Application for Intec Robots": "Next.js Web Application for Intec Robots",
            "desc1": "During my time at Intec Robots, I worked simultaneously on three projects using agile methodologies. I was part of a team responsible for developing a web application with Next.js 14. I learned to use Next.js and WebSockets for real-time communications and to create scalable web systems.",
            "React Native Application": "React Native Application (Intec Robots)",
            "desc2": "I worked on the development of a React Native application for visit management. In this project, I improved my skills in React Native, development best practices, and the integration of third-party services such as Google Calendar and video streaming.",
            "Kotlin Application for Robot Control": "Kotlin Application for Robot Control (Intec Robot)",
            "desc3": "With Android Compose, I helped improve an application to control the mini bot. In this project, I learned about different architectures like MVVM and explored the potential of Kotlin.",
            "Saas Posdcast": "Saas Podcast",
            "desc4": "SaaS for generating podcasts with real or AI voices. Create unique images for each episode and enjoy various podcasts on a Next.js platform.",
            "desc9": "This project is a To-Do App developed as part of my first internship with React. The app allows users to create, view, mark as complete, and delete tasks, providing an interactive and efficient experience. This project was an excellent opportunity to strengthen my knowledge of React and state management through React Hooks.",
            "Paw Care - Veterinary System": "Paw Care - Veterinary System",
            "desc5": "Web app for managing veterinary appointments, clients, and diagnostics. Includes pet history, online shopping with PayPal, virtual assistant, and breed recognition with AI.",
            "Library App": "Library App",
            "desc6": "Web app for managing and searching books in a library. Supervise employees and connect with PowerBI for productivity graphs.",
            "BMI App": "BMI App",
            "desc7": "Easily calculate your BMI with just two inputs. Simple and attractive design.",
            "Pet Recognition AI": "Pet Recognition AI",
            "desc8": "App to identify if a pet is a dog or a cat using AI.",
            "My work": "My Projects",
            "Projects.": "Projects.",
            "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.": "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.",
            "tecnologies Title":'Technologies',
            "navBar1":"About",
            "navBar2":"Work",
            "navBar3":"Contact",
            "navBar4":"My notes",
            "ToDoApp":"To-Do-App",
            "CalculadoraProject":"Calculator App",
            "desc10":"The application allows all users to perform mathematical operations. Using the Math.js library and hooks, I developed a calculator as a practice project when I started learning React.",
            "middenScada":"Thanks to Midden and Idrica, I gained valuable experience and knowledge in water systems. We developed a project that enabled communication among various types of sensors to issue alerts in hazardous situations. During this project, I greatly enhanced my skills in SCADA development for Qatar and in creating visual interfaces.",
            "scadaScrum":"Moreover, through this project, we learned to fully leverage the advantages of agile methodologies by using Jira and working with an excellent team. This allowed us to make significant progress and stay organized efficiently, ultimately achieving our goal of creating and communicating the status of Qatar’s water systems."
        }
    },
    es: {
        translation: {
            "Introduction": "Introducción",
            "Summary": "Resumen",
            "name":"Joaquin",
            "see":"Ver más",
            "seeCode":"Ver código",
            "heroTitle1": "Soy un Desarrollador Full Stack con experiencia en el ecosistema React (React, Next.js, React Native) y Kotlin para aplicaciones móviles nativas en Android. También he trabajado con redes neuronales, lo que me permite integrar soluciones de inteligencia artificial en mis proyectos.",
            "heroTitle2":"Mi principal objetivo es crear interfaces de usuario dinámicas y atractivas, así como servicios backend robustos y seguros, utilizando Spring Boot y Node/Express. Tengo experiencia en bases de datos SQL y NoSQL, y cuido especialmente la calidad del código, la escalabilidad y la optimización del rendimiento. Además de mi enfoque técnico, me apasiona la innovación y la resolución de problemas complejos, siempre buscando aportar valor a los usuarios finales.",
            "heroTitle3":"Creo  en la mejora continua y en el trabajo colaborativo para desarrollar soluciones de alto impacto en el mercado tecnológico.",
            "Get in touch": "Ponte en contacto",
            "Contact": "Contacto",
            "Your Name": "Tu Nombre",
            "What's your name?":"¿Cuál es tu nombre?",
            "Your email": "Tu Correo Electrónico",
            "What is your email address?":"¿Cuál es su dirección de correo electrónico?",
            "Your Message": "Tu Mensaje",
            "What you want to say?":"¿Qué es lo que quieres comunicar?",
            "Send": "Enviar",
            "Sending...": "Enviando...",
            "Hi, I'm Joaquin": "Hola, soy",
            "developer full stack, user interfaces and web applications": "Desarrollador full stack, interfaces de usuario y aplicaciones web",
            "Thank you. I will get back to you as soon as possible.": "Gracias. Me pondré en contacto contigo lo antes posible.",
            "Ahh, something went wrong. Por favor, inténtalo de nuevo.": "Ahh, algo salió mal. Por favor, inténtalo de nuevo.",
            "Featured Works": "Trabajos Destacados",
            "Next.js Web Application for Intec Robots": "Aplicación Web Next.js para Intec Robots",
            "desc1": "Durante mi tiempo en Inter Robots, trabajé simultáneamente en tres proyectos utilizando metodologías ágiles. Formé parte de un equipo encargados de desarrollar una aplicación web con Next.js 14. Aprendí a usar Next.js y WebSockets para comunicaciones en tiempo real y a crear sistemas web escalables.",
            "React Native Application": "Aplicación React Native (Intec Robots)",
            "desc2": "Trabajé en el desarrollo de una aplicación de React Native para la gestión de visitas. En este proyecto, mejoré mis habilidades en React Native, buenas prácticas de desarrollo y la integración de servicios de terceros como Google Calendar y transmisión de video.",
            "Kotlin Application for Robot Control": "Aplicación Kotlin para Control de Robots (Intec Robots)",
            "desc3": "Con Android Compose, ayudé a mejorar una aplicación para controlar el mini bot. En este proyecto, aprendí sobre diferentes arquitecturas como MVVM y exploré el potencial de Kotlin.",
            "Saas Posdcast": "Saas Podcast",
            "desc4": "SaaS para generar podcasts con voces reales o de IA. Crea imágenes únicas para cada episodio y disfruta de varios podcasts en una plataforma Next.js.",
            "Paw Care - Veterinary System": "Paw Care - Sistema Veterinario",
            "desc5": "Aplicación web para gestionar citas veterinarias, clientes y diagnósticos. Incluye historial de mascotas, compras en línea con PayPal, asistente virtual y reconocimiento de razas con IA.",
            "desc9":"Este proyecto es una aplicación de gestión de tareas (To-Do App) desarrollada como parte de mis primeras prácticas con React. La aplicación permite a los usuarios crear, visualizar, marcar como completadas y eliminar tareas, proporcionando una experiencia interactiva y eficiente. Este proyecto fue una excelente oportunidad para afianzar mis conocimientos en React y en la gestión del estado a través de React Hooks.",
            "Library App": "Sistema de Gestión Bibliotecario",
            "desc6": "Aplicación web para gestionar y buscar libros en una biblioteca. Supervisa empleados y conéctate con PowerBI para gráficos de productividad.",
            "BMI App": "Aplicación de IMC",
            "desc7": "Calcula fácilmente tu IMC con solo dos entradas. Diseño simple y atractivo.",
            "Pet Recognition AI": "IA de Reconocimiento de Mascotas",
            "desc8": "Aplicación para identificar si una mascota es un perro o un gato usando IA.",
            "My work": "Mis proyectos",
            "Projects.": "Proyectos.",
            "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.": "Los siguientes proyectos muestran mis habilidades y experiencia a través de ejemplos del mundo real de mi trabajo. Cada proyecto se describe brevemente con enlaces a repositorios de código y demostraciones en vivo. Refleja mi capacidad para resolver problemas complejos, trabajar con diferentes tecnologías y gestionar proyectos de manera efectiva.",
            "tecnologies Title":"Tecnologías",
            "middenScada": "Gracias a Midden y a Idrica, adquirí experiencia y conocimientos en sistemas hídricos. Desarrollamos un proyecto que permitía la comunicación entre diversos tipos de sensores para emitir alertas en situaciones de riesgo. En este proyecto, profundicé mis habilidades en el desarrollo de un SCADA para Qatar y en la creación de interfaces visuales.",
            "scadaScrum": "Además, a través de este proyecto aprendimos a aprovechar en gran medida las ventajas que brindan las metodologías ágiles, gracias al uso de Jira y al trabajo de un equipo de excelencia. Esto nos permitió avanzar y organizarnos de manera eficiente, cumpliendo así el objetivo de crear y comunicar el estado de los sistemas hídricos de Qatar.",
            "navBar1":"Sobre mi",
            "navBar2":"Experiencia",
            "navBar3":"Conctato",
            "navBar4":"Mis Notas",
            "ToDoApp":"To-Do-App",
            "CalculadoraProject":"Calculadora App",
            "desc10":"La aplicación permite a todos los usuarios realizar operaciones matemáticas. A través de la librería Math.js y el uso de hooks, desarrollé una calculadora como práctica al comenzar a aprender React."
        }
    }
};


i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "es", 
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;
