import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

const resources = {
    en: {
        translation: {






            "Introduction": "Introduction",
            "Summary": "Summary",
            "name":"Joaquin",
            "see":"View more",
            "timer_project_description":"Timer Box is a timer designed for boxing training and interval workouts. It allows users to configure the duration of rounds, rest periods, and the total number of repetitions. The interface is simple and intuitive, with sound effects to signal the start and end of each training phase.",
            "assistant_ia":"An intelligent virtual assistant that enhances productivity by interacting with you, searching for information on Google, reading news, and checking the weather. It also manages programs on your computer, opens and closes applications, and syncs with Google Calendar for reminders and planning. Its AI integration allows it to respond to voice or text commands, ensuring an efficient and distraction-free workflow.",
            "multi_modal_description":"An advanced conversational assistant that integrates text, voice, images, and PDF files for a more intuitive and dynamic communication experience. With AI integration, it can process and respond in multiple formats, enhancing interaction and accessibility across different platforms.",
            "seeCode":"View code",
            "heroTitle1": "I am a Full Stack Developer experienced in the React ecosystem (React, Next.js, React Native) and Kotlin for native Android applications. I have also worked with neural networks, enabling me to integrate AI solutions into my projects.",
            "heroTitle2":"My main focus is on building dynamic, engaging user interfaces and robust, secure backend services using Spring Boot and Node/Express. I bring experience with SQL and NoSQL databases, paying special attention to code quality, scalability, and performance optimization.",
            "heroTitle3":"Beyond my technical expertise, I am passionate about innovation and tackling complex problems, always striving to create genuine value for end users. I firmly believe in continuous improvement and collaborative work to develop high-impact solutions in the tech market.",
            "Get in touch": "Get in touch",
            "Contacto": "Contact",
            "Your Name": "Your Name",
            "What's your name?":"What's your name?",
            "Your email": "Your email",
            "What is your email address?":"What is your email address?",
            "Your Message": "Your Message",
            "What you want to say?":"What you want to say?",
            "Send": "Send",
            "Sending...": "Sending...",
            "Hi, I'm Joaquin": "Hi, I'm",
            "developer full stack, user interfaces and web applications": "Developer full stack, user interfaces and web applications",
            "Thank you. I will get back to you as soon as possible.": "Thank you. I will get back to you as soon as possible.",
            "Ahh, something went wrong. Please try again.": "Ahh, something went wrong. Please try again.",
            "Featured Works": "Featured Works",
            "Next.js Web Application for Intec Robots": "Next.js Web Application for Intec Robots",
            "desc1": "During my time at Intec Robots, I worked simultaneously on three projects using agile methodologies. I was part of a team responsible for developing a web application with Next.js 14. I learned to use Next.js and WebSockets for real-time communications and to create scalable web systems.",
            "React Native Application": "React Native Application (Intec Robots)",
            "desc2": "I worked on the development of a React Native application for visit management. In this project, I improved my skills in React Native, development best practices, and the integration of third-party services such as Google Calendar and video streaming.",
            "Kotlin Application for Robot Control": "Kotlin Application for Robot Control (Intec Robot)",
            "desc3": "With Android Compose, I helped improve an application to control the mini bot. In this project, I learned about different architectures like MVVM and explored the potential of Kotlin.",
            "Saas Posdcast": "Saas Podcast",
            "desc4": "SaaS for generating podcasts with real or AI voices. Create unique images for each episode and enjoy various podcasts on a Next.js platform.",
            "desc9": "This project is a To-Do App developed as part of my first internship with React. The app allows users to create, view, mark as complete, and delete tasks, providing an interactive and efficient experience. This project was an excellent opportunity to strengthen my knowledge of React and state management through React Hooks.",
            "Paw Care - Veterinary System": "Paw Care - Veterinary System",
            "desc5": "Web app for managing veterinary appointments, clients, and diagnostics. Includes pet history, online shopping with PayPal, virtual assistant, and breed recognition with AI.",
            "Library App": "Library App",
            "desc6": "Web app for managing and searching books in a library. Supervise employees and connect with PowerBI for productivity graphs.",
            "BMI App": "BMI App",
            "desc7": "Easily calculate your BMI with just two inputs. Simple and attractive design.",
            "Pet Recognition AI": "Pet Recognition AI",
            "desc8": "App to identify if a pet is a dog or a cat using AI.",
            "My work": "My Projects",
            "Projects.": "Projects.",
            "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.": "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.",
            "tecnologies Title":'Technologies',
            "navBar1":"About",
            "navBar2":"Work",
            "navBar3":"Contact",
            "navBar4":"My notes",
            "ToDoApp":"To-Do-App",
            "CalculadoraProject":"Calculator App",
            "desc10":"The application allows all users to perform mathematical operations. Using the Math.js library and hooks, I developed a calculator as a practice project when I started learning React.",
            "middenScada":"Thanks to Midden and Idrica, I gained valuable experience and knowledge in water systems. We developed a project that enabled communication among various types of sensors to issue alerts in hazardous situations. During this project, I greatly enhanced my skills in SCADA development for Qatar and in creating visual interfaces.",
            "scadaScrum":"Moreover, through this project, we learned to fully leverage the advantages of agile methodologies by using Jira and working with an excellent team. This allowed us to make significant progress and stay organized efficiently, ultimately achieving our goal of creating and communicating the status of Qatar’s water systems.",
            "FPDAMNotes": "FP Notes on Web and Multiplatform Application Development",
            "descriFPDAM": "Notes on most subjects and concepts learned in each one.",
            "JSNotes": "JavaScript Notes",
            "descipJS": "Guide and references on JavaScript, from basics to advanced.",
            "ReactNotes": "React Notes",
            "descipReact": "Essential concepts and best practices in React for web application development.",    
            "SpringNotes": "Spring Notes",
            "descipSpring": "Guide on the Spring framework for backend development with Java.",
            "VueNotes": "Vue Notes",
            "descripVue": "Introduction and development with Vue.js for building modern web applications.",
            "AWSNotes": "AWS Notes",
            "descripAWS": "Key concepts and main services of Amazon Web Services (AWS).",
            "TFNotes": "TensorFlow Notes",
            "descripTF": "Machine learning and neural networks with TensorFlow."
        }
    },
    es: {
        translation: {

          "LegalNotice":{
              "title":"AVISO LEGAL Y CONDICIONES GENERALES DE USO https://joakingc.github.io/",
              "generalInformation":{
                "title":"I. INFORMACIÓN GENERAL",
                "paragraph1":"En cumplimiento con el deber de información dispuesto en la Ley 34/2002 de Servicios de la Sociedad de la Información y el Comercio Electrónico (LSSI-CE) de 11 de julio, se facilitan a continuación los siguientes datos de información general de este sitio web:",
                "paragraph2":"La titularidad de este sitio web, https://joakingc.github.io/, (en adelante, Sitio Web) la ostenta: Gaston Joaquin Contreras, con NIF: Y9892262E, y cuyos datos de contacto son:",
                "direction":"Dirección: La cumbre 7, San Vicente de Raspeig, Alicante",
                "phone":"Teléfono de contacto: 634017310",
                "email":"Email de contacto: joakingcontreras2@gmail.com"
              },
              "generalTermsAndCondi":{
                "title":"II. TÉRMINOS Y CONDICIONES GENERALES DE USO",
                "subtitle":"El objeto de las condiciones: El Sitio Web",
                "paragraph1":"El objeto de las presentes Condiciones Generales de Uso (en adelante, Condiciones) es regular el acceso y la utilización del Sitio Web. A los efectos de las presentes Condiciones se entenderá como Sitio Web: la apariencia externa de los interfaces de pantalla, tanto de forma estática como de forma dinámica, es decir, el árbol de navegación; y todos los elementos integrados tanto en los interfaces de pantalla como en el árbol de navegación (en adelante, Contenidos) y todos aquellos servicios o recursos en línea que en su caso ofrezca a los Usuarios (en adelante, Servicios).",
                "paragraph2":"Portafolio de Joaquin Contreras se reserva la facultad de modificar, en cualquier momento, y sin aviso previo, la presentación y configuración del Sitio Web y de los Contenidos y Servicios que en él pudieran estar incorporados. El Usuario reconoce y acepta que en cualquier momento Portafolio de Joaquin Contreras pueda interrumpir, desactivar y/o cancelar cualquiera de estos elementos que se integran en el Sitio Web o el acceso a los mismos.",
                "paragraph3":"El acceso al Sitio Web por el Usuario tiene carácter libre y, por regla general, es gratuito sin que el Usuario tenga que proporcionar una contraprestación para poder disfrutar de ello, salvo en lo relativo al coste de conexión a través de la red de telecomunicaciones suministrada por el proveedor de acceso que hubiere contratado el Usuario.",
                "paragraph4":"La utilización de alguno de los Contenidos o Servicios del Sitio Web podrá hacerse mediante la suscripción o registro previo del Usuario.",
                "userTitle":"El Usuario",
                "paragraph5":"El acceso, la navegación y uso del Sitio Web, así como por los espacios habilitados para interactuar entre los Usuarios, y el Usuario y Portafolio de Joaquin Contreras, como los comentarios y/o espacios de blogging, confiere la condición de Usuario, por lo que se aceptan, desde que se inicia la navegación por el Sitio Web, todas las Condiciones aquí establecidas, así como sus ulteriores modificaciones, sin perjuicio de la aplicación de la correspondiente normativa legal de obligado cumplimiento según el caso. Dada la relevancia de lo anterior, se recomienda al Usuario leerlas cada vez que visite el Sitio Web.",
                "paragraph6":"El Sitio Web de Portafolio de Joaquin Contreras proporciona gran diversidad de información, servicios y datos. El Usuario asume su responsabilidad para realizar un uso correcto del Sitio Web. Esta responsabilidad se extenderá a:",
                "item1":"Un uso de la información, Contenidos y/o Servicios y datos ofrecidos por Portafolio de Joaquin Contreras sin que sea contrario a lo dispuesto por las presentes Condiciones, la Ley, la moral o el orden público, o que de cualquier otro modo puedan suponer lesión de los derechos de terceros o del mismo funcionamiento del Sitio Web.",
                "item2":"La veracidad y licitud de las informaciones aportadas por el Usuario en los formularios extendidos por Portafolio de Joaquin Contreras para el acceso a ciertos Contenidos o Servicios ofrecidos por el Sitio Web. En todo caso, el Usuario notificará de forma inmediata a Portafolio de Joaquin Contreras acerca de cualquier hecho que permita el uso indebido de la información registrada en dichos formularios, tales como, pero no solo, el robo, extravío, o el acceso no autorizado a identificadores y/o contraseñas, con el fin de proceder a su inmediata cancelación.",
                "paragraph7":"Portafolio de Joaquin Contreras se reserva el derecho de retirar todos aquellos comentarios y aportaciones que vulneren la ley, el respeto a la dignidad de la persona, que sean discriminatorios, xenófobos, racistas, pornográficos, spamming, que atenten contra la juventud o la infancia, el orden o la seguridad pública o que, a su juicio, no resultaran adecuados para su publicación.",
                "paragraph8":"En cualquier caso, Portafolio de Joaquin Contreras no será responsable de las opiniones vertidas por los Usuarios a través de comentarios u otras herramientas de blogging o de participación que pueda haber.",
                "paragraph9":"El mero acceso a este Sitio Web no supone entablar ningún tipo de relación de carácter comercial entre Portafolio de Joaquin Contreras y el Usuario.",
                "paragraph10":"El Usuario declara ser mayor de edad y disponer de la capacidad jurídica suficiente para vincularse por las presentes Condiciones. Por lo tanto, este Sitio Web de Portafolio de Joaquin Contreras no se dirige a menores de edad. Portafolio de Joaquin Contreras declina cualquier responsabilidad por el incumplimiento de este requisito.",
                "paragraph11":"El Sitio Web está dirigido principalmente a Usuarios residentes en España. Portafolio de Joaquin Contreras no asegura que el Sitio Web cumpla con legislaciones de otros países, ya sea total o parcialmente. Si el Usuario reside o tiene su domiciliado en otro lugar y decide acceder y/o navegar en el Sitio Web lo hará bajo su propia responsabilidad, deberá asegurarse de que tal acceso y navegación cumple con la legislación local que le es aplicable, no asumiendo Portafolio de Joaquin Contreras responsabilidad alguna que se pueda derivar de dicho acceso.",
              },
              "accessAndNavigation":{
                "title":"III. ACCESO Y NAVEGACIÓN EN EL SITIO WEB: EXCLUSIÓN DE GARANTÍAS Y RESPONSABILIDAD",
                "paragraph1":"Portafolio de Joaquin Contreras no garantiza la continuidad, disponibilidad y utilidad del Sitio Web, ni de los Contenidos o Servicios. Portafolio de Joaquin Contreras hará todo lo posible por el buen funcionamiento del Sitio Web, sin embargo, no se responsabiliza ni garantiza que el acceso a este Sitio Web no vaya a ser ininterrumpido o que esté libre de error.",
                "paragraph2":"Tampoco se responsabiliza o garantiza que el contenido o software al que pueda accederse a través de este Sitio Web, esté libre de error o cause un daño al sistema informático (software y hardware) del Usuario. En ningún caso Portafolio de Joaquin Contreras será responsable por las pérdidas, daños o perjuicios de cualquier tipo que surjan por el acceso, navegación y el uso del Sitio Web, incluyéndose, pero no limitándose, a los ocasionados a los sistemas informáticos o los provocados por la introducción de virus.",
                "paragraph3":"Portafolio de Joaquin Contreras tampoco se hace responsable de los daños que pudiesen ocasionarse a los usuarios por un uso inadecuado de este Sitio Web. En particular, no se hace responsable en modo alguno de las caídas, interrupciones, falta o defecto de las telecomunicaciones que pudieran ocurrir.",
              },
              "linksPolicy":{
                "title":"IV. POLÍTICA DE ENLACES",
                "paragraph1":"Se informa que el Sitio Web de Portafolio de Joaquin Contreras pone o puede poner a disposición de los Usuarios medios de enlace (como, entre otros, links, banners, botones), directorios y motores de búsqueda que permiten a los Usuarios acceder a sitios web pertenecientes y/o gestionados por terceros.",
                "paragraph2":"La instalación de estos enlaces, directorios y motores de búsqueda en el Sitio Web tiene por objeto facilitar a los Usuarios la búsqueda de y acceso a la información disponible en Internet, sin que pueda considerarse una sugerencia, recomendación o invitación para la visita de los mismos.",
                "paragraph3":"Portafolio de Joaquin Contreras no ofrece ni comercializa por sí ni por medio de terceros los productos y/o servicios disponibles en dichos sitios enlazados.",
                "paragraph4":"Asimismo, tampoco garantizará la disponibilidad técnica, exactitud, veracidad, validez o legalidad de sitios ajenos a su propiedad a los que se pueda acceder por medio de los enlaces.",
                "paragraph5":"Portafolio de Joaquin Contreras en ningún caso revisará o controlará el contenido de otros sitios web, así como tampoco aprueba, examina ni hace propios los productos y servicios, contenidos, archivos y cualquier otro material existente en los referidos sitios enlazados.",
                "paragraph6":"Portafolio de Joaquin Contreras no asume ninguna responsabilidad por los daños y perjuicios que pudieran producirse por el acceso, uso, calidad o licitud de los contenidos, comunicaciones, opiniones, productos y servicios de los sitios web no gestionados por Portafolio de Joaquin Contreras y que sean enlazados en este Sitio Web.",
                "paragraph7":"El Usuario o tercero que realice un hipervínculo desde una página web de otro, distinto, sitio web al Sitio Web de Portafolio de Joaquin Contreras deberá saber que:",
                "paragraph8":"No se permite la reproducción —total o parcialmente— de ninguno de los Contenidos y/o Servicios del Sitio Web sin autorización expresa de Portafolio de Joaquin Contreras.",
                "paragraph9":"No se permite tampoco ninguna manifestación falsa, inexacta o incorrecta sobre el Sitio Web de Portafolio de Joaquin Contreras, ni sobre los Contenidos y/o Servicios del mismo.",
                "paragraph10":"A excepción del hipervínculo, el sitio web en el que se establezca dicho hiperenlace no contendrá ningún elemento, de este Sitio Web, protegido como propiedad intelectual por el ordenamiento jurídico español, salvo autorización expresa de Portafolio de Joaquin Contreras.",
                "paragraph11":"El establecimiento del hipervínculo no implicará la existencia de relaciones entre Portafolio de Joaquin Contreras y el titular del sitio web desde el cual se realice, ni el conocimiento y aceptación de Portafolio de Joaquin Contreras de los contenidos, servicios y/o actividades ofrecidas en dicho sitio web, y viceversa.",
              },
              "intellectAndIndusProperty":{
                "title":"V. PROPIEDAD INTELECTUAL E INDUSTRIAL",
                "paragraph1":"Portafolio de Joaquin Contreras por sí o como parte cesionaria, es titular de todos los derechos de propiedad intelectual e industrial del Sitio Web, así como de los elementos contenidos en el mismo (a título enunciativo y no exhaustivo, imágenes, sonido, audio, vídeo, software o textos, marcas o logotipos, combinaciones de colores, estructura y diseño, selección de materiales usados, programas de ordenador necesarios para su funcionamiento, acceso y uso, etc.). Serán, por consiguiente, obras protegidas como propiedad intelectual por el ordenamiento jurídico español, siéndoles aplicables tanto la normativa española y comunitaria en este campo, como los tratados internacionales relativos a la materia y suscritos por España.",
                "paragraph2":"Todos los derechos reservados. En virtud de lo dispuesto en la Ley de Propiedad Intelectual, quedan expresamente prohibidas la reproducción, la distribución y la comunicación pública, incluida su modalidad de puesta a disposición, de la totalidad o parte de los contenidos de esta página web, con fines comerciales, en cualquier soporte y por cualquier medio técnico, sin la autorización de Portafolio de Joaquin Contreras.",
                "paragraph3":"El Usuario se compromete a respetar los derechos de propiedad intelectual e industrial de Portafolio de Joaquin Contreras. Podrá visualizar los elementos del Sitio Web o incluso imprimirlos, copiarlos y almacenarlos en el disco duro de su ordenador o en cualquier otro soporte físico siempre y cuando sea, exclusivamente, para su uso personal. El Usuario, sin embargo, no podrá suprimir, alterar, o manipular cualquier dispositivo de protección o sistema de seguridad que estuviera instalado en el Sitio Web.",
                "paragraph4":"En caso de que el Usuario o tercero considere que cualquiera de los Contenidos del Sitio Web suponga una violación de los derechos de protección de la propiedad intelectual, deberá comunicarlo inmediatamente a Portafolio de Joaquin Contreras a través de los datos de contacto del apartado de INFORMACIÓN GENERAL de este Aviso Legal y Condiciones Generales de Uso.",
              },
              "legalActions":{
                "title":"VI. ACCIONES LEGALES, LEGISLACIÓN APLICABLE Y JURISDICCIÓN",
                "paragraph1":"Portafolio de Joaquin Contreras se reserva la facultad de presentar las acciones civiles o penales que considere necesarias por la utilización indebida del Sitio Web y Contenidos, o por el incumplimiento de las presentes Condiciones.",
                "paragraph2":"La relación entre el Usuario y Portafolio de Joaquin Contreras se regirá por la normativa vigente y de aplicación en el territorio español. De surgir cualquier controversia en relación con la interpretación y/o a la aplicación de estas Condiciones las partes someterán sus conflictos a la jurisdicción ordinaria sometiéndose a los jueces y tribunales que correspondan conforme a derecho",
                "paragraph3":"Este documento de Aviso Legal y Condiciones Generales de uso del sitio web ha sido creado mediante el generador de plantilla de aviso legal y condiciones de uso online el día 04/05/2025.",
              }
            },
            "Introduction": "Introducción",
            "Summary": "Resumen",
            "name":"Joaquin",
            "see":"Ver más",
            "timer_project_description":"Timer Box es un temporizador diseñado para entrenamientos de boxeo y ejercicios por intervalos. Permite configurar la duración de los rounds, los descansos y el número total de repeticiones. Cuenta con una interfaz simple y clara, acompañada de efectos de sonido para indicar el inicio y finalización de cada fase del entrenamiento.",
            "assistant_ia":"Un asistente virtual inteligente que optimiza la productividad al interactuar contigo, buscar información en Google, leer noticias y consultar el clima. Además, gestiona programas en tu ordenador, abre y cierra aplicaciones, y se sincroniza con Google Calendar para recordatorios y planificación. Su integración con IA le permite responder a comandos de voz o texto, facilitando un flujo de trabajo eficiente y sin distracciones.",
            "seeCode":"Ver código",
            "multi_modal_description":"Un asistente conversacional avanzado que combina texto, voz, imágenes y archivos PDF para una experiencia de comunicación más intuitiva y dinámica. Gracias a su integración con IA, puede procesar y responder en múltiples formatos, mejorando la interacción y accesibilidad en distintas plataformas. ",
            "heroTitle1": "Soy un Desarrollador Full Stack con experiencia en el ecosistema React (React, Next.js, React Native) y Kotlin para aplicaciones móviles nativas en Android. También he trabajado con redes neuronales, lo que me permite integrar soluciones de inteligencia artificial en mis proyectos.",
            "heroTitle2":"Mi principal objetivo es crear interfaces de usuario dinámicas y atractivas, así como servicios backend robustos y seguros, utilizando Spring Boot y Node/Express. Tengo experiencia en bases de datos SQL y NoSQL, y cuido especialmente la calidad del código, la escalabilidad y la optimización del rendimiento. Además de mi enfoque técnico, me apasiona la innovación y la resolución de problemas complejos, siempre buscando aportar valor a los usuarios finales.",
            "heroTitle3":"Creo  en la mejora continua y en el trabajo colaborativo para desarrollar soluciones de alto impacto en el mercado tecnológico.",
            "Get in touch": "Ponte en contacto",
            "Contacto": "Contacto",
            "Your Name": "Tu Nombre",
            "What's your name?":"¿Cuál es tu nombre?",
            "Your email": "Tu Correo Electrónico",
            "What is your email address?":"¿Cuál es su dirección de correo electrónico?",
            "Your Message": "Tu Mensaje",
            "What you want to say?":"¿Qué es lo que quieres comunicar?",
            "Send": "Enviar",
            "Sending...": "Enviando...",
            "Hi, I'm Joaquin": "Hola, soy",
            "developer full stack, user interfaces and web applications": "Desarrollador full stack, interfaces de usuario y aplicaciones web",
            "Thank you. I will get back to you as soon as possible.": "Gracias. Me pondré en contacto contigo lo antes posible.",
            "Ahh, something went wrong. Por favor, inténtalo de nuevo.": "Ahh, algo salió mal. Por favor, inténtalo de nuevo.",
            "Featured Works": "Trabajos Destacados",
            "Next.js Web Application for Intec Robots": "Aplicación Web Next.js para Intec Robots",
            "desc1": "Durante mi tiempo en Inter Robots, trabajé simultáneamente en tres proyectos utilizando metodologías ágiles. Formé parte de un equipo encargados de desarrollar una aplicación web con Next.js 14. Aprendí a usar Next.js y WebSockets para comunicaciones en tiempo real y a crear sistemas web escalables.",
            "React Native Application": "Aplicación React Native (Intec Robots)",
            "desc2": "Trabajé en el desarrollo de una aplicación de React Native para la gestión de visitas. En este proyecto, mejoré mis habilidades en React Native, buenas prácticas de desarrollo y la integración de servicios de terceros como Google Calendar y transmisión de video.",
            "Kotlin Application for Robot Control": "Aplicación Kotlin para Control de Robots (Intec Robots)",
            "desc3": "Con Android Compose, ayudé a mejorar una aplicación para controlar el mini bot. En este proyecto, aprendí sobre diferentes arquitecturas como MVVM y exploré el potencial de Kotlin.",
            "Saas Posdcast": "Saas Podcast",
            "desc4": "SaaS para generar podcasts con voces reales o de IA. Crea imágenes únicas para cada episodio y disfruta de varios podcasts en una plataforma Next.js.",
            "Paw Care - Veterinary System": "Paw Care - Sistema Veterinario",
            "desc5": "Aplicación web para gestionar citas veterinarias, clientes y diagnósticos. Incluye historial de mascotas, compras en línea con PayPal, asistente virtual y reconocimiento de razas con IA.",
            "desc9":"Este proyecto es una aplicación de gestión de tareas (To-Do App) desarrollada como parte de mis primeras prácticas con React. La aplicación permite a los usuarios crear, visualizar, marcar como completadas y eliminar tareas, proporcionando una experiencia interactiva y eficiente. Este proyecto fue una excelente oportunidad para afianzar mis conocimientos en React y en la gestión del estado a través de React Hooks.",
            "Library App": "Sistema de Gestión Bibliotecario",
            "desc6": "Aplicación web para gestionar y buscar libros en una biblioteca. Supervisa empleados y conéctate con PowerBI para gráficos de productividad.",
            "BMI App": "Aplicación de IMC",
            "desc7": "Calcula fácilmente tu IMC con solo dos entradas. Diseño simple y atractivo.",
            "Pet Recognition AI": "IA de Reconocimiento de Mascotas",
            "desc8": "Aplicación para identificar si una mascota es un perro o un gato usando IA.",
            "My work": "Mis proyectos",
            "Projects.": "Proyectos.",
            "Following projects showcases my skills and experience through real-world examples of my work. Each project is briefly described with links to code repositories and live demos in it. It reflects my ability to solve complex problems, work with different technologies, and manage projects effectively.": "Los siguientes proyectos muestran mis habilidades y experiencia a través de ejemplos del mundo real de mi trabajo. Cada proyecto se describe brevemente con enlaces a repositorios de código y demostraciones en vivo. Refleja mi capacidad para resolver problemas complejos, trabajar con diferentes tecnologías y gestionar proyectos de manera efectiva.",
            "tecnologies Title":"Tecnologías",
            "middenScada": "Gracias a Midden y a Idrica, adquirí experiencia y conocimientos en sistemas hídricos. Desarrollamos un proyecto que permitía la comunicación entre diversos tipos de sensores para emitir alertas en situaciones de riesgo. En este proyecto, profundicé mis habilidades en el desarrollo de un SCADA para Qatar y en la creación de interfaces visuales.",
            "scadaScrum": "Además, a través de este proyecto aprendimos a aprovechar en gran medida las ventajas que brindan las metodologías ágiles, gracias al uso de Jira y al trabajo de un equipo de excelencia. Esto nos permitió avanzar y organizarnos de manera eficiente, cumpliendo así el objetivo de crear y comunicar el estado de los sistemas hídricos de Qatar.",
            "navBar1":"Sobre mi",
            "navBar2":"Experiencia",
            "navBar3":"Contacto",
            "navBar4":"Mis Notas",
            "ToDoApp":"To-Do-App",
            "CalculadoraProject":"Calculadora App",
            "desc10":"La aplicación permite a todos los usuarios realizar operaciones matemáticas. A través de la librería Math.js y el uso de hooks, desarrollé una calculadora como práctica al comenzar a aprender React.",
            "FPDAMNotes": "Notas de FP Desarrollo de Aplicaciones Web y Multiplataforma",
            "descriFPDAM": "Notas de la mayoría de asignaturas y conceptos aprendidos en cada una.",
            "JSNotes": "Notas de JavaScript",
            "descipJS": "Guía y referencias sobre JavaScript, desde lo básico hasta avanzado.",
            "ReactNotes": "Notas de React",
            "descipReact": "Conceptos esenciales y mejores prácticas en React para el desarrollo de aplicaciones web.",
            "SpringNotes": "Notas de Spring",
            "descipSpring": "Guía sobre el framework Spring para el desarrollo backend con Java.",
            "VueNotes": "Notas de Vue",
            "descripVue": "Introducción y desarrollo con Vue.js para la construcción de aplicaciones web modernas.",
            "AWSNotes": "Notas de AWS",
            "descripAWS": "Conceptos clave y servicios principales de Amazon Web Services (AWS).",
            "TFNotes": "Notas de TensorFlow",
            "descripTF": "Aprendizaje automático y redes neuronales con TensorFlow."
        }
    }
};


i18n
  .use(initReactI18next)
  .init({
    resources,
    lng: "es", 
    interpolation: {
      escapeValue: false 
    }
  });

export default i18n;
